### ISSUE TITLE
Integration with `howdoi`

### ISSUE THREAD

**Issue by fatiherikli** [emre/django-stackoverflow-trace#1]
Howdoi direkt stackoverflow uzerinden sonuc getiriyor. Belki boyle bir sey guzel olabilir.

https://github.com/gleitz/howdoi

**Comment by emre** [comment]
amacindan cikar ya. basit ve islevsel su an. cok da kafayi kirmamak lazim :).

**Comment by fatiherikli** [comment]
:snake:

**Comment by fatiherikli** [comment]
:cloud:
